use crate::constants::WAVE_STATE;
use crate::context::Context;
use crate::errors::{ForceLoopError, Result};
use crate::schema::CommandSchema;
use crate::state::{
    count_completed_items, count_wave_files, verify_artifact, verify_checklist, PipelineState,
};
use crate::traits::{CommandMetadata, Executable, Subcommand};

const SKILL_PROMPT: &str = "\
# Implement Skill

Develop the current wave following TDD (test first, code second).

Tracks progress via `.forceloop/wave_state.md`.

## Steps
0. Run the shell command `fl implement`.
   This checks prerequisites before proceeding.
0.2. **Git setup**: Check if `.git` directory exists in the project root.
     If not, run `git init` to initialize the repository.
0.5. **Check audit result**: Read `.forceloop/audit.md`. If the Recommendation
     is \"Blocked\", STOP and notify the user. If \"Conditional\", review any
     open audit issues that affect the current wave.
1. Read `.forceloop/wave_state.md`.
   wave_state.md is auto-generated by plan's gate — one entry per wave file.
   Do NOT regenerate it; just read it to find the current position.
2. Find the FIRST unchecked item (`- [ ]`) in wave_state.md
   from top to bottom. If none found, all waves are done.
3. Identify which wave file in `.forceloop/plans/` this item belongs to.
4. Load ONLY that one wave's plan file. Do NOT load other wave files.
   BUT DO read the existing project code (`src/`) to understand what was
   built in previous waves — the code is the source of truth for existing
   types, traits, and APIs.
4.5. **Context gathering and working tree check**: Before writing any code,
     search the existing source in `src/` for types, traits, and patterns
     relevant to this wave. Understand what previous waves built.
     Read key files this wave depends on.
     **Run `git status` and `git diff --stat`** to verify the working tree
     is clean. If there are uncommitted changes, stash or commit them first
     before proceeding. A dirty working tree between waves indicates an
     incomplete prior wave or unintended drift.
5. **Analyze wave tasks and parallelize**: Read the wave plan file to identify
   all files to create, files to modify, and implementation steps. Analyze
   their dependency relationships (e.g., if file B imports types from file A,
   B depends on A). Group the tasks into parallel batches:
   - **Batch 0** — tasks with no dependencies on other tasks in this wave
   - **Batch 1** — tasks whose dependencies (from Batch 0) are complete
   - **Batch 2+** — subsequent layers in the dependency chain

   **Execute each batch's tasks in parallel** using SubAgents (one SubAgent
   per independent task). Each SubAgent follows the TDD flow independently:
   - Write test cases for its assigned files (Red)
   - Implement the code to make those tests pass (Green)
   - Run `cargo check && cargo test` for its scope

   After all SubAgents in the current batch complete successfully, proceed
   to the next batch. Tasks with dependencies MUST wait for their
   prerequisites to finish before starting.

   **Important**: SubAgents should work on SEPARATE files to avoid edit
   conflicts. If two tasks modify the same file, they are NOT independent
   and must be serialized.

6. **Full integration validation**: After ALL parallel batches complete,
   run the full test suite across ALL changed files:
   - Run `cargo check && cargo test && cargo clippy --all-targets`
   - If any test fails, identify the breaking change, fix it, and re-run
   - Only after ALL tests pass, proceed to the next step.
7. **Commit the wave**: After all tests pass and checklists are updated,
   stage and commit the changes with a descriptive message:
   ```
   git add -A
   git commit -m \"wave: $(basename .forceloop/plans/*.md) — <brief summary>\"
   ```
   Each wave gets its own commit so the history is clean and rollback
   is straightforward for any individual wave.
8. Mark the item as completed in BOTH:
   - The wave file's own checklist in `.forceloop/plans/`
   - `.forceloop/wave_state.md` (change `- [ ]` to `- [x]`)
9. **STOP**. Do NOT continue to the next wave.
   The hook will automatically run `fl gate` to advance.
   If the gate passes and more waves remain, run `/fl-implement` again.
   If the gate fails, fix any issues, then run `/fl-implement` again.

## Constraints
- TDD mandatory: ALL tests before any code.
- No `unwrap()` in production code. No commented-out code. No debug prints.
- All checks must pass before marking an item complete.
- Do not mark items complete if tests fail.
- **Git discipline**: The working tree MUST be clean before starting a wave.
  Every wave MUST be committed before marking it complete. This ensures
  each wave is an independently revertible unit in git history.

## On Blocking Issues
If you discover the wave plan is unworkable (missing dependencies,
wrong assumptions, incompatible with existing code):
1. Note the specific blocker.
2. Update the wave file in `.forceloop/plans/` to reflect the corrected approach.
3. Also update `.forceloop/wave_state.md` if wave ordering changed.
4. Then proceed with the corrected plan.
Do NOT implement workarounds that violate the spec.
";

const COMMAND_PROMPT: &str = "\
Implement development waves following TDD.

Arguments: $ARGUMENTS

## Steps
0. Run the shell command `fl implement`.
0.2. **Git setup**: If `.git` does not exist, run `git init`.
0.5. Read `.forceloop/audit.md` — check Recommendation is not \"Blocked\".
1. Read `.forceloop/wave_state.md` (auto-generated by plan, do NOT regenerate).
2. Pick the FIRST unchecked item, find its wave file in `.forceloop/plans/`.
3. Load that wave's plan. Identify all files to create/modify and their
   dependencies. Group independent tasks for parallel execution.
   DO read existing `src/` code for context.
4. **Check working tree**: Run `git status && git diff --stat`. The working
   tree MUST be clean before starting. Stash or commit any pending changes.
5. **Parallel TDD**: For independent tasks within this wave, spawn separate
   SubAgents — each writing tests (Red), implementing (Green), and verifying
   independently on separate files. Dependent tasks serialize by batch.
6. **Integrate**: After all parallel tasks complete, run the full test suite
   together: `cargo check && cargo test && cargo clippy --all-targets`.
   Fix any cross-task integration issues.
7. **Commit the wave**: `git add -A && git commit -m \"wave: <name> — <summary>\"`
8. Update checklists in both the wave file and wave_state.md.
9. **STOP**. The hook will automatically run `fl gate` to advance.
   If the gate passes and more waves remain, run `/fl-implement` again.
   If the gate fails, fix any issues and run `/fl-implement` again.

## Constraints
- TDD mandatory. No `unwrap()` in production code. No debug prints.
- **Git discipline**: Working tree MUST be clean before each wave.
  Each wave MUST be committed before marking complete.

## On Blocking Issues
If the plan is unworkable, update the wave file in `.forceloop/plans/`
to correct the approach, then proceed. Do NOT spec-violating workarounds.
";

fn implement_skill() -> CommandSchema {
    CommandSchema {
        name: "fl-implement",
        description: "Develop the current phase (TDD)",
        model: None,
        argument_hint: Some("[phase-id]"),
        tools: &["Read", "Write", "Edit", "Bash", "Grep", "Glob"],
        agent: None,
        prompt: SKILL_PROMPT,
    }
}

fn implement_command() -> CommandSchema {
    CommandSchema {
        prompt: COMMAND_PROMPT,
        ..implement_skill()
    }
}

pub struct Implement;

impl Executable for Implement {
    fn execute(&self, _ctx: &Context) -> Result<()> {
        // 1. Read current pipeline state
        let state_path = PipelineState::locate_state_file()?;
        let state = PipelineState::read_or_default(&state_path)?;

        // 2. Check prerequisites: new, plan, and audit must be done.
        if !state.new {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: specs not ready. Run `/fl-new` first.".into(),
            ));
        }
        if !state.plan {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: plans not ready. Run `/fl-plan` first.".into(),
            ));
        }
        if !state.audit {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: audit not done. Run `/fl-audit` first.".into(),
            ));
        }

        // 3. Prerequisites met — pass to LLM via prompt.

        Ok(())
    }
}

impl Subcommand for Implement {
    fn name(&self) -> &'static str {
        "implement"
    }
    fn description(&self) -> &'static str {
        "Develop the current phase (TDD)"
    }
}

impl CommandMetadata for Implement {
    fn skill_template(&self) -> CommandSchema {
        implement_skill()
    }
    fn command_template(&self) -> CommandSchema {
        implement_command()
    }
    fn artifacts(&self) -> &[&'static str] {
        &[".forceloop/wave_state.md"]
    }
    fn check_list(&self) -> bool {
        true
    }
    fn gate(&self, _ctx: &Context) -> Result<()> {
        let forceloop_dir = PipelineState::locate_forceloop_dir()?;
        let wave_path = forceloop_dir.join(WAVE_STATE);

        // 1. Verify artifact exists and wiki links are valid.
        verify_artifact(&wave_path).map_err(|_| {
            ForceLoopError::Execution(
                "Implementation verification failed. Check wave_state.md and \
                 ensure the current wave's tasks are complete. If blocked, \
                 update the wave plan and re-run.".into(),
            )
        })?;

        // 2. Verify all checklist items in wave_state.md are completed.
        verify_checklist(&wave_path).map_err(|_| {
            ForceLoopError::Execution(
                "Implementation incomplete — checklist items remain. \
                 Complete the current wave's tasks or update the wave plan \
                 if a blocking issue was found.".into(),
            )
        })?;

        // 3. Cross-verify against actual plan files: count the number of
        //    wave FILES in .forceloop/plans/ and compare with completed
        //    waves in wave_state.md. wave_state.md tracks one entry per
        //    wave file, so both sides must count at the wave level.
        let plans_dir = forceloop_dir.join("plans");
        if plans_dir.is_dir() {
            let total_wave_files = count_wave_files(&plans_dir);
            let completed_wave_items = count_completed_items(&wave_path);
            if completed_wave_items < total_wave_files {
                let remaining = total_wave_files - completed_wave_items;
                return Err(ForceLoopError::Execution(format!(
                    "Implementation verification failed: {remaining} wave(s) \
                     not yet completed. Re-run the current wave's development \
                     tasks."
                )));
            }
        }

        Ok(())
    }
}