use crate::constants::WAVE_STATE;
use crate::context::Context;
use crate::errors::{ForceLoopError, Result};
use crate::schema::CommandSchema;
use crate::state::{
    count_completed_items, count_wave_files, verify_artifact, verify_checklist, PipelineState,
};
use crate::traits::{CommandMetadata, Executable, Subcommand};

const SKILL_PROMPT: &str = "\
# Implement Skill

Develop the current wave following TDD (test first, code second).

Tracks progress via `.forceloop/wave_state.md`.

## Steps
0. Run the shell command `fl implement`.
   This checks prerequisites before proceeding.
0.5. **Check audit result**: Read `.forceloop/audit.md`. If the Recommendation
     is \"Blocked\", STOP and notify the user. If \"Conditional\", review any
     open audit issues that affect the current wave.
1. Read `.forceloop/wave_state.md`.
   wave_state.md is auto-generated by plan's gate — one entry per wave file.
   Do NOT regenerate it; just read it to find the current position.
2. Find the FIRST unchecked item (`- [ ]`) in wave_state.md
   from top to bottom. If none found, all waves are done.
3. Identify which wave file in `.forceloop/plans/` this item belongs to.
4. Load ONLY that one wave's plan file. Do NOT load other wave files.
   BUT DO read the existing project code (`src/`) to understand what was
   built in previous waves — the code is the source of truth for existing
   types, traits, and APIs.
4.5. **Context gathering**: Before writing any code, search the existing
     source in `src/` for types, traits, and patterns relevant to this wave.
     Understand what previous waves built. Read key files this wave depends on.
     Also check `git status` that the working tree is clean.
5. Execute the development task per the wave plan. TDD flow per wave:
   - Write ALL test cases for this wave first (all Red).
     Include boundary tests, success cases, and error/failure cases.
   - Implement the code to make ALL tests pass (Green).
   - Refactor to meet code quality standards (no `unwrap()` in prod code,
     no commented-out tests, no debug prints, follow existing patterns).
   - Run `cargo check && cargo test && cargo clippy --all-targets`.
   - Only after ALL tests pass, proceed to the next step.
6. Mark the item as completed in BOTH:
   - The wave file's own checklist in `.forceloop/plans/`
   - `.forceloop/wave_state.md` (change `- [ ]` to `- [x]`)
7. The OpenCode hook calls `fl gate` automatically on idle.
   If it fails, run `/fl-implement` again to load the next wave.

## Constraints
- TDD mandatory: ALL tests before any code.
- No `unwrap()` in production code. No commented-out code. No debug prints.
- All checks must pass before marking an item complete.
- Do not mark items complete if tests fail.

## On Blocking Issues
If you discover the wave plan is unworkable (missing dependencies,
wrong assumptions, incompatible with existing code):
1. Note the specific blocker.
2. Update the wave file in `.forceloop/plans/` to reflect the corrected approach.
3. Also update `.forceloop/wave_state.md` if wave ordering changed.
4. Then proceed with the corrected plan.
Do NOT implement workarounds that violate the spec.
";

const COMMAND_PROMPT: &str = "\
Implement development waves following TDD.

Arguments: $ARGUMENTS

## Steps
0. Run the shell command `fl implement`.
0.5. Read `.forceloop/audit.md` — check Recommendation is not \"Blocked\".
1. Read `.forceloop/wave_state.md` (auto-generated by plan, do NOT regenerate).
2. Pick the FIRST unchecked item, find its wave file in `.forceloop/plans/`.
3. Load ONLY that wave's plan. DO read existing `src/` code for context.
4. Check `git status` that the working tree is clean.
5. TDD: write ALL tests (Red) → implement ALL code (Green) → refactor.
6. Run `cargo check && cargo test && cargo clippy --all-targets`.
7. Update checklists in both the wave file and wave_state.md.
8. The hook calls `fl gate` automatically. If it fails, run `/fl-implement` again.

## Constraints
- TDD mandatory. No `unwrap()` in production code. No debug prints.

## On Blocking Issues
If the plan is unworkable, update the wave file in `.forceloop/plans/`
to correct the approach, then proceed. Do NOT spec-violating workarounds.
";

fn implement_skill() -> CommandSchema {
    CommandSchema {
        name: "fl-implement",
        description: "Develop the current phase (TDD)",
        model: None,
        argument_hint: Some("[phase-id]"),
        tools: &["Read", "Write", "Edit", "Bash", "Grep", "Glob"],
        agent: None,
        prompt: SKILL_PROMPT,
    }
}

fn implement_command() -> CommandSchema {
    CommandSchema {
        prompt: COMMAND_PROMPT,
        ..implement_skill()
    }
}

pub struct Implement;

impl Executable for Implement {
    fn execute(&self, _ctx: &Context) -> Result<()> {
        // 1. Read current pipeline state
        let state_path = PipelineState::locate_state_file()?;
        let state = PipelineState::read_or_default(&state_path)?;

        // 2. Check prerequisites: new, plan, and audit must be done.
        if !state.new {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: specs not ready. Run `/fl-new` first.".into(),
            ));
        }
        if !state.plan {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: plans not ready. Run `/fl-plan` first.".into(),
            ));
        }
        if !state.audit {
            return Err(ForceLoopError::Execution(
                "Prerequisites not met: audit not done. Run `/fl-audit` first.".into(),
            ));
        }

        // 3. Prerequisites met — pass to LLM via prompt.

        Ok(())
    }
}

impl Subcommand for Implement {
    fn name(&self) -> &'static str {
        "implement"
    }
    fn description(&self) -> &'static str {
        "Develop the current phase (TDD)"
    }
}

impl CommandMetadata for Implement {
    fn skill_template(&self) -> CommandSchema {
        implement_skill()
    }
    fn command_template(&self) -> CommandSchema {
        implement_command()
    }
    fn artifacts(&self) -> &[&'static str] {
        &[".forceloop/wave_state.md"]
    }
    fn check_list(&self) -> bool {
        true
    }
    fn gate(&self, _ctx: &Context) -> Result<()> {
        let forceloop_dir = PipelineState::locate_forceloop_dir()?;
        let wave_path = forceloop_dir.join(WAVE_STATE);

        // 1. Verify artifact exists and wiki links are valid.
        verify_artifact(&wave_path).map_err(|_| {
            ForceLoopError::Execution(
                "Implementation verification failed. Check wave_state.md and \
                 ensure the current wave's tasks are complete. If blocked, \
                 update the wave plan and re-run.".into(),
            )
        })?;

        // 2. Verify all checklist items in wave_state.md are completed.
        verify_checklist(&wave_path).map_err(|_| {
            ForceLoopError::Execution(
                "Implementation incomplete — checklist items remain. \
                 Complete the current wave's tasks or update the wave plan \
                 if a blocking issue was found.".into(),
            )
        })?;

        // 3. Cross-verify against actual plan files: count the number of
        //    wave FILES in .forceloop/plans/ and compare with completed
        //    waves in wave_state.md. wave_state.md tracks one entry per
        //    wave file, so both sides must count at the wave level.
        let plans_dir = forceloop_dir.join("plans");
        if plans_dir.is_dir() {
            let total_wave_files = count_wave_files(&plans_dir);
            let completed_wave_items = count_completed_items(&wave_path);
            if completed_wave_items < total_wave_files {
                let remaining = total_wave_files - completed_wave_items;
                return Err(ForceLoopError::Execution(format!(
                    "Implementation verification failed: {remaining} wave(s) \
                     not yet completed. Re-run the current wave's development \
                     tasks."
                )));
            }
        }

        Ok(())
    }
}